### PR TITLE
ko.applyBindings requires a valid 2nd parameter if given

### LINKED ISSUE #2388: ko.applyBindings - Second Parameter
**Version**: 3.5 RC & 3.4.2

**Example**: [JSFiddle](https://jsfiddle.net/ypsjdc66/)

Via the documentation the second parameter should _restricts the activation to the element with ID someElementId and its descendants_... but when I pass in an element that doesn't exist, the applyBindings function is ignoring it. Shouldn't it fail if the element doesn't exist instead of searching the entire document?

### PR DESCRIPTION
**Pull request by mbest**
Fixes #2388

### CODE REVIEW

File: src/binding/bindingAttributeSyntax.js [hunk 1]
```diff
@@ -539,26 +539,26 @@
...
+    ko.applyBindings = function (viewModelOrBindingContext, rootNodeArg, extendContextCallback) {
         // If jQuery is loaded after Knockout, we won't initially have access to it. So save it here.
         if (!jQueryInstance && window['jQuery']) {
             jQueryInstance = window['jQuery'];
         }
 
-        // rootNode is optional
-        if (!rootNode) {
+        var rootNode = rootNodeArg;
+        if (!rootNode && arguments.length < 2) {
```
Comment (fastfasterfastest) [inline src/binding/bindingAttributeSyntax.js]: change to `if (arguments.length < 2) {`

File: src/binding/bindingAttributeSyntax.js [hunk 2]
```diff
@@ -539,26 +539,26 @@
...
-    ko.applyBindings = function (viewModelOrBindingContext, rootNode, extendContextCallback) {
+    ko.applyBindings = function (viewModelOrBindingContext, rootNodeArg, extendContextCallback) {
         // If jQuery is loaded after Knockout, we won't initially have access to it. So save it here.
         if (!jQueryInstance && window['jQuery']) {
             jQueryInstance = window['jQuery'];
         }
 
-        // rootNode is optional
-        if (!rootNode) {
+        var rootNode = rootNodeArg;
```
Comment (fastfasterfastest) [inline src/binding/bindingAttributeSyntax.js]: Why introduce another variable and not simply use `rootNodeArg`?
